# Generated by Django 5.2.16 on 2026-07-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('user', 'User'), ('admin', 'Admin'), ('freelancer', 'Freelancer')], default='user', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('client', 'Client'), ('user', 'User'), ('admin', 'Admin'), ('freelancer', 'Freelancer')], default='client', max_length=20),
        ),
    ]
